### ISSUE TITLE
Plugin not installing correctly - Http Request Error

### ISSUE THREAD

**Issue by aaron38** [Plambt/Puzzle2020#2]
https://github.com/Plambt/Puzzle2020/blob/7c6b54929750de8d452f7d67901fec5445852712/OpenPlanetUpdater/src/Main.as#L3

leads to the following error:
`Script exception: Http Request has not yet finished - use Finished() before calling this function`

Looking at [this update](https://openplanet.dev/news/2022/plugin-configs), adding 
 ```
while (!ScriptVersion.Finished()) {
        	yield();
    	};
```

directly after the line fixes this (i tried it)

**Comment by Plambt** [comment]
Done and Published.
Waiting for OP approval.
